# This is a basic workflow to help you get started with Actions

name: Coding

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Push to coding
    - name: Push to coding
      env:
          ACTION_DEPLOY_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan e.coding.net >> ~/.ssh/known_hosts
        git config --global user.name 'zz5840'
        git config --global user.email 'zz5840@qq.com'
        rm -rf .git
        git init
        git remote add origin git@e.coding.net:zz5840/banground-wiki/bangbangboom-editor.git
        git push -uf
